Repository OpenSmock/Molecule, pull requests merged in 2024-10, with the labels that each got.

#189 enhancements and code refactoring - using MolUtils
  src/Molecule-Tests/MolCompleteComponentOverloadImpl.class.st
  src/Molecule-Tests/MolLocatorServicesTest.class.st
  src/Molecule/MolComponentFactory.class.st
  src/Molecule/MolUtils.class.st
Labels: enhancement

#193 Fix #133
  src/Molecule-Tests/MolComponentAnnouncementTest.class.st
  src/Molecule-Tests/MolComponentEventsTest.class.st
  src/Molecule-Tests/MolComponentImplTest.class.st
  src/Molecule-Tests/MolComponentParametersTest.class.st
  src/Molecule-Tests/MolComponentServicesTest.class.st
  src/Molecule-Tests/MolComponentTypeTest.class.st
  src/Molecule-Tests/MolExtensionsTest.class.st
  src/Molecule/MolComponentImpl.trait.st
  src/Molecule/Object.extension.st
Labels: technical work

#194 Write test for #190
  src/Molecule-IDE-Tests/MolWorldTest.class.st
  src/Molecule-IDE/MolDefineComponentCmdCommand.class.st
  src/Molecule-IDE/MolWorld.class.st
Labels: bug

#200 Fix #198 and #199
  src/Molecule-IDE/MolImplementationsPresenter.class.st
  src/Molecule-Tests/MolCompleteComponentChild2Impl.class.st
  src/Molecule-Tests/MolUtilsTest.class.st
  src/Molecule/MolUtils.class.st
Labels: bug
